name: RotatingHeadsPlus
main: com.me.koyere.rotatingheadsplus.RotatingHeadsPlus
version: 1.0.0
api-version: 1.20
author: Koyere
website: https://www.spigotmc.org/resources/rotatingheadsplus.00000/
description: Adds rotating heads, armor stands and entities with customizable animations.

commands:
  rhead:
    description: Main command for creating and managing rotating heads/entities.
    usage: /rhead <create|remove|list|reload|help>
    aliases: [rheads, rh]

permissions:
  rotatingheadsplus.use:
    description: Allows usage of all /rhead commands.
    default: true
  rotatingheadsplus.admin:
    description: Allows access to /rhead reload and admin functions.
    default: op

softdepend:
  - PlaceholderAPI
  - HolographicDisplays
  - DecentHolograms
